# Generated by Django 4.1 on 2022-09-14 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecast',
            old_name='city',
            new_name='zipcode',
        ),
    ]
